# Generated by Django 2.2.20 on 2021-04-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
    ]
